/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentInboxRouteImport } from './routes/student/inbox'
import { Route as StudentMessagesRouteImport } from './routes/student/messages'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentRoommatesRouteImport } from './routes/student/roommates'
import { Route as StudentSavingsRouteImport } from './routes/student/savings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentInboxRoute = StudentInboxRouteImport.update({
  id: '/student/inbox',
  path: '/student/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/student/messages',
  path: '/student/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoommatesRoute = StudentRoommatesRouteImport.update({
  id: '/student/roommates',
  path: '/student/roommates',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSavingsRoute = StudentSavingsRouteImport.update({
  id: '/student/savings',
  path: '/student/savings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/inbox': typeof StudentInboxRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/roommates': typeof StudentRoommatesRoute
  '/student/savings': typeof StudentSavingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/inbox': typeof StudentInboxRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/roommates': typeof StudentRoommatesRoute
  '/student/savings': typeof StudentSavingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/inbox': typeof StudentInboxRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/roommates': typeof StudentRoommatesRoute
  '/student/savings': typeof StudentSavingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/student/dashboard'
    | '/student/inbox'
    | '/student/messages'
    | '/student/profile'
    | '/student/roommates'
    | '/student/savings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/student/dashboard'
    | '/student/inbox'
    | '/student/messages'
    | '/student/profile'
    | '/student/roommates'
    | '/student/savings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/student/dashboard'
    | '/student/inbox'
    | '/student/messages'
    | '/student/profile'
    | '/student/roommates'
    | '/student/savings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentInboxRoute: typeof StudentInboxRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRoommatesRoute: typeof StudentRoommatesRoute
  StudentSavingsRoute: typeof StudentSavingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/inbox': {
      id: '/student/inbox'
      path: '/student/inbox'
      fullPath: '/student/inbox'
      preLoaderRoute: typeof StudentInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/student/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/roommates': {
      id: '/student/roommates'
      path: '/student/roommates'
      fullPath: '/student/roommates'
      preLoaderRoute: typeof StudentRoommatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/savings': {
      id: '/student/savings'
      path: '/student/savings'
      fullPath: '/student/savings'
      preLoaderRoute: typeof StudentSavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentInboxRoute: StudentInboxRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRoommatesRoute: StudentRoommatesRoute,
  StudentSavingsRoute: StudentSavingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
